// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:gym_track/hive/hive_adapters.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AppSettingsAdapter());
    registerAdapter(BiologicalSexAdapter());
    registerAdapter(EquipmentAdapter());
    registerAdapter(ExerciseAdapter());
    registerAdapter(ExerciseCategoryAdapter());
    registerAdapter(ExerciseSetAdapter());
    registerAdapter(ExerciseTrackingAdapter());
    registerAdapter(GoalAdapter());
    registerAdapter(GoalDirectionAdapter());
    registerAdapter(GoalStatusAdapter());
    registerAdapter(GoalTypeAdapter());
    registerAdapter(MuscleGroupAdapter());
    registerAdapter(PhotoPoseAdapter());
    registerAdapter(PlanDifficultyAdapter());
    registerAdapter(PlanExerciseAdapter());
    registerAdapter(ProgressPhotoAdapter());
    registerAdapter(SessionExerciseAdapter());
    registerAdapter(SetTypeAdapter());
    registerAdapter(ThemePreferenceAdapter());
    registerAdapter(UnitSystemAdapter());
    registerAdapter(WeightEntryAdapter());
    registerAdapter(WorkoutPlanAdapter());
    registerAdapter(WorkoutSessionAdapter());
    registerAdapter(WorkoutStatusAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(AppSettingsAdapter());
    registerAdapter(BiologicalSexAdapter());
    registerAdapter(EquipmentAdapter());
    registerAdapter(ExerciseAdapter());
    registerAdapter(ExerciseCategoryAdapter());
    registerAdapter(ExerciseSetAdapter());
    registerAdapter(ExerciseTrackingAdapter());
    registerAdapter(GoalAdapter());
    registerAdapter(GoalDirectionAdapter());
    registerAdapter(GoalStatusAdapter());
    registerAdapter(GoalTypeAdapter());
    registerAdapter(MuscleGroupAdapter());
    registerAdapter(PhotoPoseAdapter());
    registerAdapter(PlanDifficultyAdapter());
    registerAdapter(PlanExerciseAdapter());
    registerAdapter(ProgressPhotoAdapter());
    registerAdapter(SessionExerciseAdapter());
    registerAdapter(SetTypeAdapter());
    registerAdapter(ThemePreferenceAdapter());
    registerAdapter(UnitSystemAdapter());
    registerAdapter(WeightEntryAdapter());
    registerAdapter(WorkoutPlanAdapter());
    registerAdapter(WorkoutSessionAdapter());
    registerAdapter(WorkoutStatusAdapter());
  }
}
